[project]
name = "ProyectoPOO"
version = "0.1.0"
description = "Implementar una soluciÃ³n en base a la programaciÃ³n orientada a objetos y conectarla a una base de datos."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
